### ISSUE TITLE
Background Image pattern is shifted

### ISSUE THREAD

**Issue by Bruzzlee** [sarahmonster/pique#2]
Every background image pattern starts ca. 150 pix below the top of the web browser. 
At a screen resolution of 2560 x 1440.
Tested with Safari, Firefox, Chrome on OSX
This behaviour can also be reproduced on the demo page: https://piquedemo.wordpress.com but there it is less noticeable because of the uniform contrast of the background images and the "Start using this theme on your blog." - bar.
To gain this effect one can enlarge the browser to 2000 pixel height or use a image which fades from red to blue.

**Comment by sarahmonster** [comment]
I passed this issue along to the theme's maintainers and this bug has since been fixed on .com.

The panel's background image has been adjusted so that it vertically aligns to top of the panel, rather than to the center. This prevents shorter images from repeating near the top of the panel and should result in a better experience for all users.

Thanks for the bug report!
